import {
  FaHtml5,
  FaCss3,
  FaSass,
  FaBootstrap,
  FaGitAlt,
  FaReact,
  FaNode,
  FaPhp
} from "react-icons/fa";

import { IoLogoJavascript } from "react-icons/io5";

import { SiTailwindcss, SiJquery, SiExpress, SiMysql } from "react-icons/si";

import { TbBrandNextjs, TbBrandReactNative } from "react-icons/tb";

import { BiLogoMongodb } from "react-icons/bi";


export const skills = {
  frontEnd: [
    {
      name: "HTML",
      icon: <FaHtml5 />,
      classnames: 'hover:text-[#f06529]'
    },
    {
      name: "CSS",
      icon: <FaCss3 />,
      classnames: 'hover:text-[#264de4]'
    },
    {
      name: "Javascript",
      icon: <IoLogoJavascript />,
      classnames: 'hover:text-[#f7df1e]'
    },
    {
      name: "Sass",
      icon: <FaSass />,
      classnames: 'hover:text-[#cc6699]'
    },
    {
      name: "Bootstrap",
      icon: <FaBootstrap />,
      classnames: 'hover:text-[#563d7c]'
    },
    {
      name: "Tailwind",
      icon: <SiTailwindcss />,
      classnames: 'hover:text-[#06b6d4]'
    },
    {
      name: "Git",
      icon: <FaGitAlt />,
      classnames: 'hover:text-[#f1502f]'
    },
    {
      name: "React",
      icon: <FaReact />,
      classnames: 'hover:text-[#06b6d4]'
    },
    {
      name: "Next",
      icon: <TbBrandNextjs />,
      classnames: ''
    },
    {
      name: "jQuery",
      icon: <SiJquery />,
      classnames: 'hover:text-[#7ACEF4]'
    },
  ],
  backEnd: [
    {
      name: "Mongodb",
      icon: <BiLogoMongodb />,
      classnames: 'hover:text-[#589636]'
    },
    {
      name: "Express",
      icon: <SiExpress />,
      classnames: 'hover:text-[#000]'
    },
    {
      name: "Nodejs",
      icon: <FaNode />,
      classnames: 'hover:text-[#3c873a]'
    },
    {
      name: "SQL",
      icon: <SiMysql />,
      classnames: 'hover:text-[#00758F]'
    },
    {
      name: "Php",
      icon: <FaPhp />,
      classnames: 'hover:text-[#777BB3]'
    },
  ],
  mobile: [
    {
      name: "React Native",
      icon: <TbBrandReactNative />,
      classnames: 'hover:text-[#06b6d4]'
    }
  ],
};

export const certificates = {
  frontEnd: [
    {
      id: '1',
      type: 'Specialization',
      name: "Meta Front-End Developer",
      organizer: "Meta and offered through Coursera",
      date: new Date('02-16-2023'),
      description: `This certificate is issued to demonstrate that the recipient has completed Approximately 7 months at 6 hours a week to complete successfully Meta Front-End Developer Specialization.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Meta%20Front-End%20Developer.webp?alt=media&token=f5dbc513-2126-45c9-be75-a6646767acaf",
      link: "https://www.coursera.org/account/accomplishments/professional-cert/FGAZLY6WUUFD",
      innerCertificates: [
        {
          id: "0",
          name: "Meta Front-End Developer",
          organizer: "Meta and offered through Coursera",
          date: new Date('02-16-2023'),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Meta%20Front-End%20Developer.webp?alt=media&token=f5dbc513-2126-45c9-be75-a6646767acaf",
          link: "https://www.coursera.org/account/accomplishments/professional-cert/FGAZLY6WUUFD",
        },
        {
          id: "1",
          name: "Coding Interview Preparation",
          date: new Date("02-16-2023"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Coding%20Interview%20Preparation.webp?alt=media&token=ed7d1b96-1269-4f6e-b168-d0295325c051",
          link: "https://www.coursera.org/account/accomplishments/certificate/CSWPB2JKURLE",
        },
        {
          id: "2",
          name: "Front-End Developer Capstone",
          date: new Date("02-08-2023"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Front-End%20Developer%20Capstone.webp?alt=media&token=d712e5a4-af20-4e10-8417-b1a13030c49c",
          link: "https://www.coursera.org/account/accomplishments/certificate/K44YPSRXG2DE",
        },
        {
          id: "3",
          name: "Principles of UX/UI Design",
          date: new Date("01-11-2023"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Principles%20of%20UX-UI%20Design.webp?alt=media&token=aa5bdf25-4fa7-4361-817d-0906d294b505",
          link: "https://www.coursera.org/account/accomplishments/certificate/ZQHP3HWR6VBQ",
        },
        {
          id: "4",
          name: "Advanced React",
          date: new Date("01-19-2023"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Advanced%20React.webp?alt=media&token=ed9148aa-d4f6-40a1-b575-374e31358139",
          link: "https://www.coursera.org/account/accomplishments/certificate/PKQ84B7JSVUY",
        },
        {
          id: "5",
          name: "React Basics",
          date: new Date("10-15-2022"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20React%20Basics.webp?alt=media&token=64bee64d-e952-4937-a666-17cb9ab5e1ec",
          link: "https://www.coursera.org/account/accomplishments/certificate/9ZY4MJH5TCUZ",
        },
        {
          id: "6",
          name: "HTML and CSS in depth",
          date: new Date("01-12-2023"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20HTML%20and%20CSS%20in%20depth.webp?alt=media&token=7b561dc0-3d43-41f9-86bd-b0c837213016",
          link: "https://www.coursera.org/account/accomplishments/certificate/25JYB7H3PJPA",
        },
        {
          id: "7",
          name: "Version Control",
          date: new Date("08-12-2022"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Version%20Control.webp?alt=media&token=5bdbc435-1481-4d56-a2c4-850201fe84bc",
          link: "https://www.coursera.org/account/accomplishments/certificate/5XZUDH9Y2YYE",
        },
        {
          id: "8",
          name: "Programming with JavaScript",
          date: new Date("07-29-2022"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Programming%20with%20JavaScript.webp?alt=media&token=fb92f9dd-35cf-43ea-b8d4-80da08f9b0d7",
          link: "https://www.coursera.org/account/accomplishments/certificate/XAWUQ7A8MHYW",
        },
        {
          id: "9",
          name: "Introduction to Front-End Development",
          date: new Date("07-17-2022"),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Front-End%20Development.webp?alt=media&token=e1ca80ac-6152-447b-84b7-e28269d40b0d",
          link: "https://www.coursera.org/account/accomplishments/certificate/9EHELMD9V6DK",
        },
      ],
    },
    {
      id: "2",
      type: 'Specialization',
      name: "Web Design for Everybody: Basics of Web Development & Coding",
      organizer: "University of Michigan and offered through Coursera",
      date: new Date('03-01-2022'),
      description: `This certificate is issued to demonstrate that the recipient has completed Approximately 2 months at 10 hours a week to complete successfully Web Design for Everybody: Basics of Web Development & Coding Specialization`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Web%20Design%20for%20Everybody%20Basics%20of%20Web%20Development%20%26%20Coding.webp?alt=media&token=ab7c1fee-e2fb-44f0-8b4a-7a9f4f0c0752",
      link: "https://www.coursera.org/account/accomplishments/specialization/YTKZZEZ5JTAP",
      innerCertificates: [
        {
          id: "0",
          name: "Web Design for Everybody: Basics of Web Development & Coding",
          date: new Date('03-01-2022'),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Web%20Design%20for%20Everybody%20Basics%20of%20Web%20Development%20%26%20Coding.webp?alt=media&token=ab7c1fee-e2fb-44f0-8b4a-7a9f4f0c0752",
          link: "https://www.coursera.org/account/accomplishments/specialization/YTKZZEZ5JTAP",
        },
        {
          id: "1",
          name: "Web Design for Everybody Capstone",
          date: new Date('03-01-2022'),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Web%20Design%20for%20Everybody%20Capstone.webp?alt=media&token=e27f9050-21de-4064-a78d-0003a67359fb",
          link: "https://www.coursera.org/account/accomplishments/certificate/DRW9CHT3C9Z6",
        },
        {
          id: "2",
          name: "Advanced Styling with Responsive Design",
          date: new Date('01-07-2022'),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Advanced%20Styling%20with%20Responsive%20Design.webp?alt=media&token=c8ccb15c-2b1a-41be-9106-813b9c3dc3a5",
          link: "https://www.coursera.org/account/accomplishments/certificate/RULZE2E2XVN8",
        },
        {
          id: "3",
          name: "Interactivity with JavaScript",
          date: new Date('12-30-2021'),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Interactivity%20with%20JavaScript.webp?alt=media&token=199b3b08-4ba8-41d4-b0ba-694373be46eb",
          link: "https://www.coursera.org/account/accomplishments/certificate/FPVJEQ8XTKPR",
        },
        {
          id: "4",
          name: "Introduction to CSS3",
          date: new Date('12-11-2021'),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20CSS3.webp?alt=media&token=b541c580-df6b-45db-afe6-14031f306870",
          link: "https://www.coursera.org/account/accomplishments/certificate/WX563M9UCCX3",
        },
        {
          id: "5",
          name: "Introduction to HTML5",
          date: new Date('11-17-2021'),
          img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20HTML5.webp?alt=media&token=2529990d-2a8f-41db-9337-9c727980b61b",
          link: "https://www.coursera.org/account/accomplishments/certificate/T833KHCWCKRP",
        },
      ],
    },
    {
      id: "3",
      type: 'Course',
      name: "Developing Front-End Apps with React",
      organizer: "IBM and offered through Coursera",
      date: new Date('03-07-2023'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Developing Front-End Apps with React Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Developing%20Front-End%20Apps%20with%20React.webp?alt=media&token=25960a5b-8f6b-4f97-b2f8-b80a991824cd",
      link: "https://www.coursera.org/account/accomplishments/certificate/6VLPULVJ2J9D",
    },
    {
      id: "4",
      type: 'Course',
      name: "Build Your First React Website",
      organizer: "Coursera Project Network and offered through Coursera",
      date: new Date('11-12-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Build Your First React Website Project`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Build%20Your%20First%20React%20Website.webp?alt=media&token=789eb3eb-7ed4-4418-b29f-ae6c1544f010",
      link: "https://www.coursera.org/account/accomplishments/certificate/B78VKSTGZL48",
    },
    {
      id: "5",
      type: 'Course',
      name: "JavaScript Basics",
      organizer: " University of California, Davis and offered through Coursera",
      date: new Date('07-31-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a JavaScript Basics Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20JavaScript%20Basics.webp?alt=media&token=38abafee-2377-4ad5-8873-62712c576f5a",
      link: "https://www.coursera.org/account/accomplishments/certificate/33XBYUMLVPKG",
    },
    {
      id: "6",
      type: 'Course',
      name: "Developing Responsive Web Pages Using HTML5 and CSS3",
      organizer: "NIIT and offered through Coursera",
      date: new Date('06-09-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Developing Responsive Web Pages Using HTML5 and CSS3 Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Developing%20Responsive%20Web%20Pages%20Using%20HTML5%20and%20CSS3.webp?alt=media&token=0fed0e8b-7b01-4a1a-9a15-a82fc80ba272",
      link: "https://www.coursera.org/account/accomplishments/certificate/LP7FDBNMDM96",
    },
    {
      id: "7",
      type: 'Course',
      name: "Getting Started with Git and GitHub",
      organizer: "IBM and offered through Coursera",
      date: new Date('06-03-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Getting Started with Git and GitHub Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Getting%20Started%20with%20Git%20and%20GitHub.webp?alt=media&token=a3d4d5e2-7c65-4298-935e-342268e37000",
      link: "https://www.coursera.org/account/accomplishments/certificate/EQT4HXDYYQVN",
    },
    {
      id: "8",
      type: 'Course',
      name: "Introduction to Web Development with HTML, CSS, JavaScript",
      organizer: "IBM and offered through Coursera",
      date: new Date('12-29-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Web Development with HTML, CSS, JavaScript Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Web%20Development%20with%20HTML%2C%20CSS%2C%20JavaScript.webp?alt=media&token=90672e34-f017-4a44-b1d5-d9ce1c236275",
      link: "https://www.coursera.org/account/accomplishments/certificate/NJEH9AEWRKVT",
    },
    {
      id: "9",
      type: 'Course',
      name: "Introduction to building Web Pages using HTML5 and CSS3",
      organizer: "NIIT and offered through Coursera",
      date: new Date('06-02-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to building Web Pages using HTML5 and CSS3 Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20building%20Web%20Pages%20using%20HTML5%20and%20CSS3.webp?alt=media&token=1e66feac-673e-417f-acfc-31613ed6de91",
      link: "https://www.coursera.org/account/accomplishments/certificate/W8YN79RPPQFC",
    },
    {
      id: "10",
      type: 'Course',
      name: "HTML, CSS, and Javascript for Web Developers",
      organizer: "Johns Hopkins University and offered through Coursera",
      date: new Date('01-11-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a HTML, CSS, and Javascript for Web Developers Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20HTML%2C%20CSS%2C%20and%20Javascript%20for%20Web%20Developers.webp?alt=media&token=e482d9ca-85b7-4705-9264-3227d994a6e5",
      link: "https://www.coursera.org/account/accomplishments/certificate/LAP9THC6ZMH4",
    },
    {
      id: "11",
      type: 'Course',
      name: "Responsive Website Basics: Code with HTML, CSS, and JavaScript",
      organizer: " University of London and Goldsmiths, University of London and offered through Coursera",
      date: new Date('01-03-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Responsive Website Basics: Code with HTML, CSS, and JavaScript Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Responsive%20Website%20Basics-%20Code%20with%20HTML%20CSS%20and%20JavaScript.webp?alt=media&token=02e0b834-e915-46a1-a3bd-b86a46c58688",
      link: "https://www.coursera.org/account/accomplishments/certificate/W8PJWF2CDA5J",
    },
    {
      id: "12",
      type: 'Course',
      name: "Programming Foundations with JavaScript, HTML and CSS",
      organizer: "Duke University and offered through Coursera",
      date: new Date('12-30-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Programming Foundations with JavaScript, HTML and CSS Course `,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Programming%20Foundations%20with%20JavaScript%2C%20HTML%20and%20CSS.webp?alt=media&token=ca489f1c-d3c1-4678-8620-19b4bf2f1fe0",
      link: "https://www.coursera.org/account/accomplishments/certificate/FU83AUV3D3BB",
    },
    {
      id: "13",
      type: 'Course',
      name: "Introduction to Web Development",
      organizer: "University of California, Davis and offered through Coursera",
      date: new Date('12-22-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Web Development Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Web%20Development.webp?alt=media&token=8acb083a-0d46-41f0-be8e-3443c314170a",
      link: "https://www.coursera.org/account/accomplishments/certificate/6P7V9F5CKD3U",
    },
    {
      id: "14",
      type: 'Course',
      name: "CS50x: CS50's Introduction to Computer Science",
      organizer: "HarvardX, an online learning initiative of Harvard University.",
      date: new Date('08-27-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a CS50x: CS50's Introduction to Computer Science Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FHarvard%20cs50.webp?alt=media&token=9540d518-813e-4041-b8f3-38f9bc8fff14",
      link: "https://courses.edx.org/certificates/b02af443590c4919b1678900d16abb9e",
    },
    {
      id: "15",
      type: 'Course',
      name: "Responsive Web Design",
      organizer: "FreeCodeCamp",
      date: new Date('10-26-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Responsive Web Design Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Ffreecodecamp%20Responsive%20web%20design.webp?alt=media&token=3a021759-373a-430f-9841-0af6b6ce4133",
      link: "https://www.freecodecamp.org/certification/fcc05b0a456-76e8-4a45-869c-8d33597320dd/responsive-web-design",
    },
    {
      id: "16",
      type: 'Course',
      name: "JavaScript Algorithms and Data Structures",
      organizer: "FreeCodeCamp",
      date: new Date('02-11-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a JavaScript Algorithms and Data Structures Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Ffreecodecamp%20JavaScript%20Algorithms%20and%20Data%20Structures.webp?alt=media&token=da5a40b5-cb74-4c7f-a166-d79d0cb36b92",
      link: "https://www.freecodecamp.org/certification/fcc05b0a456-76e8-4a45-869c-8d33597320dd/javascript-algorithms-and-data-structures",
    },
    {
      id: "17",
      type: 'Course',
      name: "JavaScript Essential Training",
      organizer: "LinkedIn Learning",
      date: new Date('06-29-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a JavaScript Essential Training Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20JavaScript%20Essential%20Training.webp?alt=media&token=fb7f5356-a50b-4e73-925b-0787d5540534",
      link: "https://www.linkedin.com/learning/certificates/a0d2d262060477ca0ee85761c1ad8602bdf08df7d6c03da35506bb865a9c9d8b",
    },
    {
      id: "18",
      type: 'Course',
      name: "CSS Essential Training (2019)",
      organizer: "LinkedIn Learning",
      date: new Date('08-27-2020'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a CSS Essential Training (2019) Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20CSS%20Essential%20Training.webp?alt=media&token=1261b8b8-2fa0-4889-b6ec-24370dbf4eda",
      link: "https://www.linkedin.com/learning/certificates/c92f3761bbb6b017c37b81e47ddc8eba7ff50337f4e7a1e00ecd3efd67f69fdf",
    },
    {
      id: "19",
      type: 'Course',
      name: "HTML Essential Training",
      organizer: "LinkedIn Learning",
      date: new Date('08-13-2020'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a HTML Essential Training Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20HTML%20Essential%20Training.webp?alt=media&token=5fa23382-5e75-4fa6-a624-aa2258149505",
      link: "https://www.linkedin.com/learning/certificates/677c60f8b21bdf1bf66e6d24b4cf90331af09dbd58d3c07242bcaad12ca21dda",
    },
    {
      id: "20",
      type: 'Course',
      name: "JavaScript Essential Training (2017)",
      organizer: "LinkedIn Learning",
      date: new Date('09-05-2020'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a JavaScript Essential Training (2017) Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20JavaScript%20Essential%20Training.webp?alt=media&token=fb7f5356-a50b-4e73-925b-0787d5540534",
      link: "https://www.linkedin.com/learning/certificates/e163332eed10568ef3da2830b113070f247e1283a042a913f4cdca51116d5fd9",
    },
    {
      id: "21",
      type: 'Course',
      name: "React + Redux",
      organizer: "Sololearn",
      date: new Date('05-21-2023'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a React + Redux course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20react%20%2B%20redux.webp?alt=media&token=352f615e-264d-42f7-9165-41dd8103bd39",
      link: "https://www.sololearn.com/en/certificates/CT-LK8FXD6S",
    },
    {
      id: "22",
      type: 'Course',
      name: "Responsive Web Design",
      organizer: "Sololearn",
      date: new Date('10-01-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Responsive Web Design Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20responsive%20web%20design.webp?alt=media&token=c3a044a3-e476-4541-88a0-322dff4c5773",
      link: "https://www.sololearn.com/en/certificates/CT-TDSTYR5F",
    },
    {
      id: "23",
      type: 'Course',
      name: "JavaScript",
      organizer: "Sololearn",
      date: new Date('09-22-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a JavaScript Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20javascript.webp?alt=media&token=5f216068-637e-492f-abcf-5b98724e555f",
      link: "https://www.sololearn.com/en/certificates/CT-6BYJEKSN",
    },
    {
      id: "24",
      type: 'Course',
      name: "CSS",
      organizer: "Sololearn",
      date: new Date('07-26-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a CSS Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20css.webp?alt=media&token=7b0d662e-1fc1-43a3-b711-14dbcb9902cc",
      link: "https://www.sololearn.com/en/certificates/CT-2XCZIODQ",
    },
    {
      id: "25",
      type: 'Course',
      name: "HTML",
      organizer: "Sololearn",
      date: new Date('07-21-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a HTML Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20html.webp?alt=media&token=78d9b81e-c4b3-47fe-af1b-29c4df7c0797",
      link: "https://www.sololearn.com/en/certificates/CT-IGUGOXB8",
    },
    {
      id: "26",
      type: 'Course',
      name: "jQuery",
      organizer: "Sololearn",
      date: new Date('03-14-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a jQuery Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20jQuery.webp?alt=media&token=765838b7-12ab-420e-b3ad-327fb332a2ea",
      link: "https://www.sololearn.com/en/certificates/CT-BBUALQSY",
    },
    {
      id: "27",
      type: 'Course',
      name: "Web Development Fundamentals",
      organizer: "Sololearn",
      date: new Date('03-21-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Web Development Fundamentals Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20web%20development%20fundamentals.webp?alt=media&token=f56707d0-fc5f-47a7-85db-10eb90848055",
      link: "https://www.sololearn.com/en/certificates/CT-CGP1MW70",
    },
    {
      id: "28",
      type: 'Course',
      name: "Game Development with JS",
      organizer: "Sololearn",
      date: new Date('03-22-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Game Development with JS Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20game%20development%20with%20js.webp?alt=media&token=9de56fbf-aa31-4af2-bab2-5829dd9f24f8",
      link: "https://www.sololearn.com/en/certificates/CT-1GJK90NK"
    },
    {
      id: "29",
      type: 'Course',
      name: "React (Basic)",
      organizer: "HackerRank",
      date: new Date('11-20-2023'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a React (Basic) Certificate`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fhacker-rank%20React(Basics).webp?alt=media&token=324834d5-20cd-491d-86ed-e1cfda0017eb",
      link: "https://www.hackerrank.com/certificates/d37080e5f708",
    },
    {
      id: "30",
      type: 'Course',
      name: "CSS (Basic)",
      organizer: "HackerRank",
      date: new Date('05-17-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a CSS (Basic) Certificate`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fhackerrank%20css.webp?alt=media&token=8d2578fb-b521-40ec-8d59-e7907d32b594",
      link: "https://www.hackerrank.com/certificates/70ea85305e27",
    },
    {
      id: "31",
      type: 'Course',
      name: "Learn JavaScript - For Beginners",
      organizer: "Udemy",
      date: new Date('09-26-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Learn JavaScript - For Beginners Course`,
      img: "https://udemy-certificate.s3.amazonaws.com/image/UC-5edd6c4b-9277-47a4-8e46-92410fd88941.jpg?v=1632627160000",
      link: "https://www.udemy.com/certificate/UC-5edd6c4b-9277-47a4-8e46-92410fd88941/",
    },
    {
      id: "32",
      type: 'Course',
      name: "Front End Development Track",
      organizer: "Udacity",
      date: new Date('09-1-2020'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Front End Development Track`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fudacity%20front%20end%20track.webp?alt=media&token=88aca71d-f001-4042-95ba-1fd5d00e35d0",
      link: "",
    },
    {
      id: "33",
      type: 'Course',
      name: "Web Development Challenger Track",
      organizer: "Udacity",
      date: new Date('10-1-2020'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Web Development Challenger Track`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fegypt%20fwd%20Web%20development%20Track.webp?alt=media&token=1a4949d0-398a-483f-ba17-03367c6fd9c5",
      link: "",
    },


  ],
  backEnd: [
    {
      id: "1",
      type: 'Course',
      name: "Developing Back-End Apps with Node.js and Express",
      organizer: "IBM and offered through Coursera",
      date: new Date('05-16-2023'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Developing Back-End Apps with Node.js and Express Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursers%20Developing%20Back-End%20Apps%20with%20Node-js%20and%20express.webp?alt=media&token=0f49a116-b739-461a-9a6d-10eee0299789",
      link: "https://www.coursera.org/account/accomplishments/certificate/WT5HSS7Z4BDG",
    },
    {
      id: "2",
      type: 'Course',
      name: "Introduction to Databases for Back-End Development",
      organizer: "Meta and offered through Coursera",
      date: new Date('10-28-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Databases for Back-End Development Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Databases%20for%20Back-End.webp?alt=media&token=4675d803-76fb-4e8b-8936-8305cf920446",
      link: "https://www.coursera.org/account/accomplishments/certificate/VU4EA2BRRD9Z"
    },
    {
      id: "3",
      type: 'Course',
      name: "Introduction to Databases",
      organizer: "Meta and offered through Coursera",
      date: new Date('10-28-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Databases Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Databases%20(2).webp?alt=media&token=620fad6c-2051-442e-aeda-1902a4a0d581",
      link: "https://www.coursera.org/account/accomplishments/certificate/7QRKHU9RXDMP"
    },
    {
      id: "4",
      type: 'Course',
      name: "Introduction to Back-End Development",
      organizer: "Meta and offered through Coursera",
      date: new Date('07-17-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Back-End Development Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Back-End%20Development.webp?alt=media&token=158a6bd8-2bfc-45b6-982d-7ae56de65bda",
      link: "https://www.coursera.org/account/accomplishments/certificate/YY4VSK8LGL6F"
    },
    {
      id: "5",
      type: 'Course',
      name: "Introduction to Structured Query Language (SQL)",
      organizer: "University of Michigan and offered through Coursera",
      date: new Date('05-02-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Structured Query Language (SQL) Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Structured%20Query%20Language%20(SQL).webp?alt=media&token=4c4dda92-bbde-49dc-9ed1-6b5142d107ed",
      link: "https://www.coursera.org/account/accomplishments/certificate/W9GN4ZHW7YFP"
    },
    {
      id: "6",
      type: 'Course',
      name: "Building Web Applications in PHP",
      organizer: "University of Michigan and offered through Coursera",
      date: new Date('02-18-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Building Web Applications in PHP Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Building%20Web%20Applications%20in%20PHP.webp?alt=media&token=c32b79bb-76e3-494e-a81f-81521c5d41f3",
      link: "https://www.coursera.org/account/accomplishments/certificate/LXDY596RNXAH"
    },
    {
      id: "7",
      type: 'Course',
      name: "Introduction to Data Analytics",
      organizer: "IBM and offered through Coursera",
      date: new Date('01-07-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Data Analytics Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Data%20Analytics.webp?alt=media&token=c35f7dce-0ab6-46ba-9821-533d10e0dff7",
      link: "https://www.coursera.org/account/accomplishments/certificate/U5R7GJXHLJKX"
    },
    {
      id: "8",
      type: 'Course',
      name: "The Structured Query Language (SQL)",
      organizer: "University of Colorado Boulder and offered through Coursera",
      date: new Date('06-29-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed The Structured Query Language (SQL) Course`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20The%20Structured%20Query%20Language%20(SQL).webp?alt=media&token=4f446d78-80e7-45a6-a8fc-acc3ea785fbd",
      link: "https://www.coursera.org/account/accomplishments/certificate/5A47LUCEGBHX"
    },
    {
      id: "9",
      type: 'Course',
      name: "Foundations: Data, Data, Everywhere",
      organizer: "Google and offered through Coursera",
      date: new Date('12-24-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Foundations: Data, Data, Everywhere Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Foundations%20Data%2C%20Data%2C%20Everywhere.webp?alt=media&token=668a3e92-e1e9-4e19-96e8-f1e2a5c206d2",
      link: "https://www.coursera.org/account/accomplishments/certificate/6RCPF2DE33BS"
    },
    {
      id: "10",
      type: 'Course',
      name: "Learning SQL Programming",
      organizer: "LinkedIn Learning",
      date: new Date('06-18-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a Learning SQL Programming Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Learning%20SQL%20Programming.webp?alt=media&token=578c3161-f522-403f-89e9-6512e2c343e4",
      link: "https://www.linkedin.com/learning/certificates/a27506674bb18cdff77fcbbcfe6bf99ac1e45cdbd70e42953372b05b54df89b0"
    },
    {
      id: "11",
      type: 'Course',
      name: "SQL",
      organizer: "Sololearn",
      date: new Date('07-23-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a SQL Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20sql.webp?alt=media&token=70f8229a-f8a9-4460-abdf-c295120fd9cd",
      link: "https://www.sololearn.com/en/certificates/CT-DHY1IYNO"
    },
    {
      id: "12",
      type: 'Course',
      name: "PHP",
      organizer: "Sololearn",
      date: new Date('03-09-2022'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a PHP Course.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20php.webp?alt=media&token=d9f439ca-e692-48a1-bfd5-9b508d20fb96",
      link: "https://www.sololearn.com/en/certificates/CT-XCJWTHC6"
    },
    {
      id: "13",
      type: 'Course',
      name: "SQL (Basic)",
      organizer: "HackerRank",
      date: new Date('07-22-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a SQL (Basic) Certificate.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fhackerrank%20SQL%20basic%20certificate.webp?alt=media&token=aa1fd0ea-2012-4d24-8b76-12a7518855e9",
      link: "https://www.hackerrank.com/certificates/a931353d55d0"
    },
    {
      id: "14",
      type: 'Course',
      name: "SQL (Intermediate)",
      organizer: "HackerRank",
      date: new Date('09-03-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a SQL (Intermediate) Certificate.`,
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fhackerrank%20SQL%20intermediate%20certificate.webp?alt=media&token=f2dac46f-2caa-4b20-b42a-caa6e9bf8c1f",
      link: "https://www.hackerrank.com/certificates/d962f7cad8b4"
    },
    {
      id: "14",
      type: 'Course',
      name: "SQL- The Complete Introduction to SQL programming",
      organizer: "Udemy",
      date: new Date('06-24-2021'),
      description: `This certificate is issued to demonstrate that the recipient has successfully completed a SQL- The Complete Introduction to SQL programming Course.`,
      img: "https://udemy-certificate.s3.amazonaws.com/image/UC-79c13ff2-c4a2-4bc2-a773-8069edc27138.jpg?v=1624554103000",
      link: "https://www.udemy.com/certificate/UC-79c13ff2-c4a2-4bc2-a773-8069edc27138/"
    },
  ],
  other: [
    {
      id: "1",
      type: 'Course',
      name: "Introduction to Android Mobile Application Development",
      organizer: "Meta and offered through Coursera",
      date: new Date('11-15-2022'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Android Mobile Application Development Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Android%20Mobile%20Application.webp?alt=media&token=44f574a8-4d88-4f21-a913-2ab37cb993ba",
      link: "https://www.coursera.org/account/accomplishments/certificate/83XEQ7545DF4",
    },
    {
      id: "2",
      type: 'Course',
      name: "Work Smarter with Microsoft Word",
      organizer: "Microsoft and offered through Coursera",
      date: new Date('08-12-2022'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Work Smarter with Microsoft Word Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Work%20Smarter%20with%20Microsoft%20Word.webp?alt=media&token=357f56b6-8058-48c7-bdd0-fd5c154d135a",
      link: "https://www.coursera.org/account/accomplishments/certificate/XBABYURQ9ZFQ",
    },
    {
      id: "3",
      type: 'Course',
      name: "Introduction to Mobile Development",
      organizer: "Meta and offered through Coursera",
      date: new Date('08-28-2022'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Mobile Development Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Mobile%20Development.webp?alt=media&token=159a69b9-0b0a-4c31-95ef-bdc0bbf501b1",
      link: "https://www.coursera.org/account/accomplishments/certificate/ZAR3BMTN9BYU",
    },
    {
      id: "4",
      type: 'Course',
      name: "C for Everyone: Programming Fundamentals",
      organizer: "University of California, Santa Cruz and offered through Coursera",
      date: new Date('12-24-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a C for Everyone: Programming Fundamentals Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20C%20for%20Everyone%20Programming%20Fundamentals.webp?alt=media&token=4b282d43-b992-4e18-8b0f-823805ed2841",
      link: "https://www.coursera.org/account/accomplishments/certificate/KBLLZY9VTPFL",
    },
    {
      id: "5",
      type: 'Course',
      name: "What is Data Science?",
      organizer: "IBM and offered through Coursera",
      date: new Date('12-18-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a What is Data Science? Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20What%20is%20Data%20Science.webp?alt=media&token=91afb13d-0dc7-4f02-8e71-3093c0a7bad2",
      link: "https://www.coursera.org/account/accomplishments/certificate/Y9RBXR3FXHNP",
    },
    {
      id: "6",
      type: 'Course',
      name: "Introduction to Java",
      organizer: "LearnQuest and offered through Coursera",
      date: new Date('12-18-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Java Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Java.webp?alt=media&token=fe1c3611-3765-46c9-b7c4-4b915dbe7c4d",
      link: "https://www.coursera.org/account/accomplishments/certificate/EXNCDZ3UNVQ7",
    },
    {
      id: "7",
      type: 'Course',
      name: "Introduction to Cloud Computing",
      organizer: "IBM and offered through Coursera",
      date: new Date('12-03-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Cloud Computing Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Introduction%20to%20Cloud%20Computing.webp?alt=media&token=c0cfbd8d-2629-436e-8678-479d48352a02",
      link: "https://www.coursera.org/account/accomplishments/certificate/2NLJG334Z692",
    },
    {
      id: "8",
      type: 'Course',
      name: "Code Yourself! An Introduction to Programming",
      organizer: "The University of Edinburgh and Universidad ORT Uruguay and offered through Coursera",
      date: new Date('11-15-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Code Yourself! An Introduction to Programming Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2FCoursera%20Code%20Yourself!%20An%20Introduction%20to%20Programming.webp?alt=media&token=54f304ac-e7f2-4dd6-944a-6644659804bf",
      link: "https://www.coursera.org/account/accomplishments/certificate/CBGAFGPWXSAU",
    },
    {
      id: "9",
      type: 'Course',
      name: "Learning Python (2020)",
      organizer: "LinkedIn Learning",
      date: new Date('06-24-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Learning Python (2020) Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Learning%20Python.webp?alt=media&token=3c16652b-faa1-4bb1-b117-8ee52ed480e3",
      link: "https://www.linkedin.com/learning/certificates/6a3ec4784b565922a9764718714ecf2490e4ccc43ff286bdfe5c35fa6fd51ffa",
    },
    {
      id: "10",
      type: 'Course',
      name: "Succeeding in Web Development: Full Stack and Front End",
      organizer: "LinkedIn Learning",
      date: new Date('08-04-2020'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Succeeding in Web Development: Full Stack and Front End Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Succeeding%20in%20Web%20Development%20Full%20Stack%20and%20Front%20End.webp?alt=media&token=fbb7ba0f-4b11-4fce-a56b-44964b054d64",
      link: "https://www.linkedin.com/learning/certificates/dbd899602bfbbe4c6f7780c682587d05633480e2afc132632a33e1c6784048ce",
    },
    {
      id: "11",
      type: 'Course',
      name: "Programming Foundations: Databases",
      organizer: "LinkedIn Learning",
      date: new Date('07-19-2020'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Programming Foundations: Databases Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Programming%20Foundations%20Databases.webp?alt=media&token=cb9ca2f0-752c-4cfc-aa21-3a49074a389a",
      link: "https://www.linkedin.com/learning/certificates/7a74c7b5e2ee321a94b831ec00cd773b8482a8c327c6265c7aa0fc91ea177584",
    },
    {
      id: "12",
      type: 'Course',
      name: "Programming Foundations: Fundamentals",
      organizer: "LinkedIn Learning",
      date: new Date('07-14-2020'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Programming Foundations: Fundamentals Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Programming%20Foundations%20Fundamentals.webp?alt=media&token=50bd0e7b-f266-4084-a8a9-b3d80354e9f5",
      link: "https://www.linkedin.com/learning/certificates/f3c74897829b6836f80718f0983f93785412b63ac036adc5fd86aabcf4717963",
    },
    {
      id: "13",
      type: 'Course',
      name: "Color for Design and Art",
      organizer: "LinkedIn Learning",
      date: new Date('08-28-2020'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Color for Design and Art Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Color%20for%20Design%20and%20Art.webp?alt=media&token=63d2cf48-cfe4-4924-b531-7696fca82698",
      link: "https://www.linkedin.com/learning/certificates/890f2fc8cfcd2eb914ce4ce63c09cd89757c63b81e6eda18a180dcdfdf10b005",
    },
    {
      id: "14",
      type: 'Course',
      name: "Graphic Design Foundations: Typography (2013)",
      organizer: "LinkedIn Learning",
      date: new Date('08-24-2020'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Graphic Design Foundations: Typography (2013) Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Graphic%20Design%20Foundations%20Typography.webp?alt=media&token=12b3a244-7b69-48e3-b5bf-0104a2aedbfb",
      link: "https://www.linkedin.com/learning/certificates/ec3faeecfdaac962282e3ed1211cb3acf3099ce20ca4df3b8ca8e1b331d6f918",
    },
    {
      id: "15",
      type: 'Course',
      name: "Graphic Design Foundations: Layout and Composition (2013)",
      organizer: "LinkedIn Learning",
      date: new Date('08-15-2020'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Graphic Design Foundations: Layout and Composition (2013) Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Graphic%20Design%20Foundations%20Layout%20and%20Composition.webp?alt=media&token=1ac039a8-57f4-47b3-ac39-ef6c63f3af35",
      link: "https://www.linkedin.com/learning/certificates/764162b866d407e03f1e7f85edb7e189cf6387220b064619e97694cbcb7d6354",
    },
    {
      id: "16",
      type: 'Course',
      name: "Introduction to Graphic Design",
      organizer: "LinkedIn Learning",
      date: new Date('08-08-2020'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Introduction to Graphic Design Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Flinkedin%20Introduction%20to%20Graphic%20Design.webp?alt=media&token=4e1bf9b5-e3b0-4afa-bb52-f187f8182034",
      link: "https://www.linkedin.com/learning/certificates/d447bb844705e62d037548be290377b076c31198cc6bd6303ed0076b8b0e13e0",
    },
    {
      id: "17",
      type: 'Course',
      name: "Python for Beginners",
      organizer: "Sololearn",
      date: new Date('07-17-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Python for Beginners Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20python%20for%20beginners.webp?alt=media&token=41bf730d-b1f8-4e35-ac65-2a47d54d7da4",
      link: "https://www.sololearn.com/en/certificates/CT-H2WBG4BA",
    },
    {
      id: "18",
      type: 'Course',
      name: "Coding for Maketers",
      organizer: "Sololearn",
      date: new Date('03-12-2022'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Coding for Maketers Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20coding%20for%20marketers.webp?alt=media&token=92f8e0c7-4ff5-4940-8482-3d8f2b669bb6",
      link: "https://www.sololearn.com/en/certificates/CT-MXE7HZTC",
    },
    {
      id: "19",
      type: 'Course',
      name: "C++",
      organizer: "Sololearn",
      date: new Date('09-28-2022'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a C++ Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fsololearn%20c%2B%2B.webp?alt=media&token=0a04ce54-a47c-4325-b997-c233c270ff44",
      link: "https://www.sololearn.com/en/certificates/CT-KDKYF2QT",
    },
    {
      id: "20",
      type: 'Course',
      name: "Python (Basic)",
      organizer: "HackerRank",
      date: new Date('09-13-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Python (Basic) Certificate',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2Fhackerrank%20python%20basic%20certificate.webp?alt=media&token=c7e013fe-c6a2-4c57-8e15-a83071131993",
      link: "https://www.hackerrank.com/certificates/92d05a840f11",
    },
    {
      id: "21",
      type: 'Course',
      name: "Complete Wordpress Website Developer Course",
      organizer: "Udemy",
      date: new Date('07-05-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Complete Wordpress Website Developer Course  Course',
      img: "https://udemy-certificate.s3.amazonaws.com/image/UC-ef862a81-52fd-43b2-b433-fc0b0ff20360.jpg?v=1626490758000",
      link: "https://www.udemy.com/certificate/UC-ef862a81-52fd-43b2-b433-fc0b0ff20360/",
    },
    {
      id: "22",
      type: 'Course',
      name: "Learn Python Basics",
      organizer: "Udemy",
      date: new Date('06-21-2021'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Learn Python Basics Course',
      img: "https://udemy-certificate.s3.amazonaws.com/image/UC-c81e5bd5-5ab6-414d-9a86-04eb3c50a194.jpg?v=1624287470000",
      link: "https://www.udemy.com/certificate/UC-c81e5bd5-5ab6-414d-9a86-04eb3c50a194/",
    },
    {
      id: "23",
      type: 'Certificate',
      name: "International Computer driving license (ICDL)",
      organizer: "Computer Sciences and Technology Information Training Center, Kafr ElSheikh, Egypt.",
      date: new Date('07-04-2018'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed the International Computer driving license (ICDL)',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2F14.webp?alt=media&token=cc749e3b-2e7b-4f93-b28b-5f626b65a031",
      link: "https://icdlarabia.org/e/46AC0A",
    },
    {
      id: "24",
      type: 'Course',
      name: "Windows-Internet-programming Concepts",
      organizer: "Arabic Group for Computer (AGC), Tanta, Egypt",
      date: new Date('05-15-2010'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Windows-Internet-programming Concepts Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2F15.webp?alt=media&token=d52ab002-2707-4c8f-b73e-4dd7617c28f1",
      link: "",
    },
    {
      id: "25",
      type: 'Course',
      name: "Advanced Project system Company",
      organizer: "Arabic Group for Computer (AGC), Tanta, Egypt",
      date: new Date('03-15-2010'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a Advanced Project system Company Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2F16.webp?alt=media&token=ffdfa665-0017-4817-9e5f-4f70e2f15b71",
      link: "",
    },
    {
      id: "26",
      type: 'Course',
      name: "PC Maintenance (Hardware & Software) L I, I I",
      organizer: "Computer Sciences and Technology Information Training Center, Kafr El-Sheikh, Egypt.",
      date: new Date('09-12-2005'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a PC Maintenance (Hardware & Software) L I, I I Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2F18.webp?alt=media&token=310d530f-381d-4af5-9973-187f5c412fe7",
      link: "",
    },
    {
      id: "27",
      type: 'Course',
      name: "Introd., Windows, MS – Office 2000 (word, Excel) LI & Internet",
      organizer: "Computer Sciences and Technology Information Training Center, Kafr El-Sheikh, Egypt.",
      date: new Date('09-05-2005'),
      description: 'This certificate is issued to demonstrate that the recipient has successfully completed a  Course',
      img: "https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/certificates%2F17.webp?alt=media&token=a3093022-a0ac-4fa1-94fb-ff60a6b36824",
      link: "",
    },

  ]
};


export const portfolio = [

  {
    name: 'this.Portfolio😉',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fportfolio-v2.webp?alt=media&token=e4c389b1-3dd4-49ae-be93-6e916e4ef0eb',
    repo: 'https://github.com/elshafie/elshafie.github.io',
    live: './',
    description: `This is a personal Portfolio website that showcases my skills in web development using ReactJS library along with other technologies like ThreeJs, Saas, Tailwind`,
    skills: ['Vite', 'Tailwind', 'Sass', 'ThreeJs']
  },
  {
    name: 'Portfolio V1',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fportfolio-v1.webp?alt=media&token=c90851ef-53c6-400f-8cd3-93600cdf434d',
    repo: 'https://github.com/elshafie/portfolio-v1',
    live: 'https://elshafie.github.io/portfolio-v1/',
    description: 'This is a personal Portfolio website version1',
    skills: ['HTML', 'CSS', 'JavaScript']
  },
  {
    name: 'E-commerce-app',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2FE-commerce.webp?alt=media&token=08fb53ae-3e35-4573-b731-1a82c8fe9f7b',
    repo: 'https://github.com/elshafie/ecommerce-app',
    live: 'https://bewildered-pike-sunglasses.cyclic.app/',
    description: `A simple eCommerce app built with React, Redux, Node.js, Express server, MongoDB database`,
    skills: ['Mongodb', 'Express', 'React', 'Node', 'Css']
  },
  {
    name: 'Tech-Note App',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fteck-notes.webp?alt=media&token=f76a3c01-c6b1-4a6e-b31d-afc1c88699eb',
    repo: 'https://github.com/elshafie/technotes/tree/main',
    live: 'https://technotes-j3xv.onrender.com/',
    description: `An application to keep track of tech related notes using React, Redux, Node.js, Express server, MongoDB database`,
    skills: ['Mongodb', 'Express', 'React', 'Node', 'Css']
  },
  {
    name: 'Tinder Clone',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Ftinder-clone.webp?alt=media&token=84b6e922-f4ef-4cbc-868a-7788a6f010f7',
    repo: 'https://github.com/elshafie/tinder/tree/main',
    live: 'https://tinder-mpwi.onrender.com/',
    description: "A Tinder like dating app clone made using React and Firebase",
    skills: ['Mongodb', 'Express', 'React', 'Node', 'Css', 'Material UI', 'axios']
  },
  {
    name: 'Weather App',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fweather-app.webp?alt=media&token=af86dc22-9ade-4bc6-b48a-9d75fd87a363',
    repo: 'https://github.com/elshafie/weather-app',
    live: 'https://elshafie.github.io/weather-app/',
    description: 'A weather application that shows the current weather of a city based on user input',
    skills: ['HTML', 'CSS', 'JavaScript', 'Weather API']
  },
  {
    name: 'Animal production Station',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fsakha-station.webp?alt=media&token=71b8b47b-611f-4f28-871e-da95c38ff29d',
    repo: 'https://github.com/elshafie/animal-station',
    live: 'https://elshafie.github.io/animal-station/',
    description: 'Capstone project for my web development course. It is an animal production station website.',
    skills: ['HTML', 'CSS', 'JavaScript']
  },
  {
    name: 'Video Landing Page',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fvideo-landing.webp?alt=media&token=0e707929-f7a7-46cb-8980-805bda6113b0',
    repo: 'https://github.com/elshafie/project/tree/main/video-landing-page',
    live: 'https://elshafie.github.io/project/video-landing-page/',
    description: 'A responsive video landing page for an online course platform',
    skills: ['HTML', 'CSS', 'JavaScript']
  },
  {
    name: 'Elshafie Template',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Felshafie-template.webp?alt=media&token=396bc7f3-b881-44e8-970b-eb68deb2c926',
    repo: 'https://github.com/elshafie/elshafie-template',
    live: 'https://elshafie.github.io/elshafie-template/',
    description: 'A template to start any project quickly with basic HTML, CSS & JavaScript setup',
    skills: ['HTML', 'CSS', 'JavaScript']
  },
  {
    name: 'Kasper',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fkasper.webp?alt=media&token=d608abfd-9fb8-4ece-bf80-501fe6f3d449',
    repo: 'https://github.com/elshafie/kasper',
    live: 'https://elshafie.github.io/kasper/',
    description: 'A simple portfolio website showcasing my projects and skills',
    skills: ['HTML', 'CSS', 'JavaScript']
  },
  {
    name: 'Leon',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fleon.webp?alt=media&token=3be886fd-aea7-4010-a93a-28fa107f80a2',
    repo: 'https://github.com/elshafie/leon',
    live: 'https://elshafie.github.io/leon/',
    description: "A one-page resume website built using only HTML and CSS",
    skills: ['HTML', 'CSS', 'JavaScript']
  },
  {
    name: 'Parallax Landing Page',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fparallax-site.webp?alt=media&token=75857a2b-c84f-4f3a-89a0-bae3e8d05ea2',
    repo: 'https://github.com/elshafie/scrolling-website',
    live: 'https://elshafie.github.io/scrolling-website/',
    description: 'A parallax scrolling effect on a landing page',
    skills: ['HTML', 'CSS', 'JavaScript']
  },
  {
    name: 'Animated Landing Page',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/storage-15.appspot.com/o/portfolio%2Fanimated-websiate.webp?alt=media&token=c837077f-7756-4886-a153-714c5e820753',
    repo: 'https://github.com/elshafie/animated-website',
    live: 'https://elshafie.github.io/animated-website/',
    description: 'An animated landing page with hover effects',
    skills: ['HTML', 'CSS', 'JavaScript']
  },

]